### ISSUE TITLE
Code for Figure 4 Experiment

### ISSUE THREAD

**Issue by tuwangwenx** [jmiemirza/DUA#1]
Hello.Thanks for a very nice paper and open code. Would you have an example code for other experiments ?

**Comment by jmiemirza** [comment]
Hi, Thanks for interest in our paper. The code for the Object Detection experiments follow closely the code for Image Classification experiments. We plan to release the code for object detection in the future because it is not yet cleaned up. It is built upon the open source [YOLOv3 code from ultralytics](https://github.com/ultralytics/yolov3).

As soon as we release the code, I will let you know. Or if you are in a hurry. Please send me an email and I can share the unrefined code.

**Comment by tuwangwenx** [comment]
> Hi, Thanks for interest in our paper. The code for the Object Detection experiments follow closely the code for Image Classification experiments. We plan to release the code for object detection in the future because it is not yet cleaned up. It is built upon the open source [YOLOv3 code from ultralytics](https://github.com/ultralytics/yolov3).
> 
> As soon as we release the code, I will let you know. Or if you are in a hurry. Please send me an email and I can share the unrefined code.
Thanks for reply,I had a few questions and it would be great if you could help me understand this better.
In figure3,you use default parameters and you say the adaptation performance is either unstable or convergesrather slowly."This is because with the default parametersthe adaptation of the running mean and variance is highly unstable." 
1.I don't understand why using the fixed momentum  parameter will become unstable or slow convergence. 
2.Why does the convergence speed become faster and more stable by using the method you proposed in the paper？
3.When will you provide code for other experiments？

**Comment by jmiemirza** [comment]
Hi, I will try to answer your questions in a systematic manner. 

1. The answer to this question is lying in the figure. 1 on the first page. You see that using the default momentum parameters (e.g. 0.1) can lead to very unstable convergence. Now if we change this parameter to, e.g. 0.01, we see that the convergence is stable but the problem is that it is slow. Now using DUA's adaptive momentum schema, we see that we can have a good tradeoff between convergence speed and stability (figure. 1, Blue line). 
2. Simply because we are using an adaptive momentum scheme and not a fixed momentum. This can be understood by the equations 4, 5, 6, 7. 
3. The code still isn't refined yet. I will update the repo soon. 

Best Regards, 
Mirza.
